---
- hosts: webservers
  vars:
  - warName: helloworld.war
  - warRemotePath: /path/to/put/war

  tasks:
    - name: example copying file with owner and permissions
      copy:
        src: /var/jenkins_home/workspace/ansible-2/index.jsp
        dest: /opt/apache-tomcat-8.5.57/webapps/webapp
